---
title: 'Evolution of pre-copulatory and post-copulatory inbreeding behaviour'
author: "A. Bradley Duthie et al."
date: "August 24, 2016"
output:
  pdf_document:
    fig_caption: yes
  html_document: default
  word_document:
    fig_caption: yes
    pandoc_args:
    - --csl
    - evolution.csl
header-includes:
- \usepackage{natbib}
- \usepackage{lineno}
- \linenumbers
- \bibliographystyle{amnatnat}
linestretch: 1
csl: evolution.csl
bibliography: ms_pre_post.bib
---

<!--- Need to do 40k generations to see allele values level off, 40 replicates each:

Figure    1: 100 hours total
Figures   2: 48  hours total
Figures   3: 48  hours total
Figures   4: 48  hours total
Figures   5: 48  hours total

Nah, these are too much. I've decided to increase to 40k generations for the costs only (100 hours total). Reasoning for this is that when we look at the fixed traits, we are really interested in whether or not the initial invasion changes, hence fewer generations are better. When we start everything at zero and let it evolve, then long-term stuff becomes more important, so 40k are useful.

--->


******************************

Abstract
===================================================

Inbreeding avoidance has been widely observed through pre-copulatory and post-copulatory mechanisms as a consequence of inbreeding depression in offspring viability. However, no conceptual framework compares evolution of pre-copulatory and post-copulatory inbreeding avoidance jointly, and given biologically relevant costs of inbreeding strategies. Critically, evolution of post-copulatory inbreeding avoidance is restricted to females that mate multiply, potentially leading to complex evolutionary dynamics among inbreeding strategies and polyandry. Accordingly, we use individual-based modelling to track evolution of polyandry and inbreeding strategies under multiple costs and constraints to address three questions: Will evolution of post-copulatory inbreeding avoidance strengthen selection for polyandry? Will selection for one costly inbreeding strategy be negligible given a non-costly complementary strategy? And will selection for one inbreeding strategy be negligible given existence of an already adaptive alternative strategy? We show that evolution of polyandry is greatly facilitated by post-copulatory inbreeding avoidance. Strong selection for relatively low cost inbreeding avoidance strategies was observed, while selection for functionally redundant high cost strategies decreased over generations. Finally, existence of an adaptive inbreeding strategy precluded evolution of post-copulatory, but not pre-copulatory, inbreeding avoidance. Our model thereby introduces a novel framework for predicting evolution of both pre-copulatory and post-copulatory inbreeding strategies in empirical systems.

Introduction
===================================================

<!--- Reproductive decisions expressed among interacting individuals directly affect individual fitnesses and the genotypes and viabilities of resulting offspring, and thereby profoundly affect evolutionary dynamics through the differential inheritence of alleles over generations [@Pizzari2012; @Wright2013; @Wild2014; @Liao2015; @Reid2016]. For example, how frequently a focal female mates is a reproductive decision that can directly and indirectly affect her fitness, and potentially alter the distribution of genotypes and patterns of inheritence within a population [e.g., @Cornell2007; @Diaz2010; @Okada2015; @Roberts2015a; @Worthington2016]. Her mating frequency and expression of mate choice might be affected by the genetic quality or complementarity of available potential mates, and her choosiness might additionally be expressed after mating has taken place through post-copulatory mechanisms [@Parker1983; @Parker2006; @Kuijper2012]. Female choice might therefore be realised by evolution of multiple, potentially interdependent, behavioural and physiological phenotypes operating in tandem. However, no general modelling framework predicts the conditions under which female mating frequency, pre-copulatory choice, and post-copulatory choice evolve together, meaning that there are no formal hypotheses for predicting the relevance of these reproductive decisions across different biological systems. --->

Polyandry, defined as female multiple mating within a single reproductive bout, is a reproductive strategy that simultaneously allows females to choose multiple mates and creates the opportunity for further cryptic choice enacted through post-copulatory mechanisms. One key choice for females is the decision to prefer, avoid, or tolerate breeding with relatives ['inbreeding'; @Szulkin2012]. Inbreeding often reduces the fitness of inbred offspring [@Charlesworth1999; @Keller2002; @Charlesworth2009], and polyandry has been widely hypothesised to evolve as an adaptation to allow females to reduce their inbreeding and therefore produce higher fitness offspring [@Zeh1997; @Jennions2000; @Tregenza2002; @Akcay2007]. In a recent model, @Duthie showed that selection for alleles underlying polyandry and pre-copulatory inbreeding avoidance occurred only under highly constrained conditions in which direct costs of polyandry were low, and when very few males were available during a female's initial mate choice but many males were available during a female's additional mate choice(s), or when polyandry was conditionally expressed based on the degree to which a focal female engaged in inbreeding given her initially chosen mate. In the absence of these constraints, expression of polyandry was expected to increase inbreeding with each additional mate because remaining males were more likely to be relatives once available non-relatives were chosen. However, @Duthie assumed that polyandrous females had no control over the assignment of paternity to their offspring. If after engaging in polyandry, females could bias paternity through post-copulatory mechanisms, then selection for polyandry to avoid inbreeding might be more widely predicted when inbreeding depression is severe [@Zeh1997].

<!--- I fear we're starting down a rabbit hole here. ---> 
Severe inbreeding depression might cause selection for alleles underlying active pre- and post-copulatory inbreeding avoidance and associated polyandry, but if evolution of one strategy renders its complement redundant for avoiding inbreeding, then selection might instead be sustained over generations for only one strategy. Empirical studies of multiple species have found evidence for female pre-copulatory inbreeding avoidance [e.g., @Lihoreau2007; @Kuriwada2011; @Kingma2013; @Fischer2015], and for post-copulatory inbreeding avoidance [e.g., @Simmons2006; @Bretman2009]. Further, evidence of both pre-copulatory and post-copulatory inbreeding avoidance has been found for a handful of well-studied species, including Trinidadian guppies [*Poecilia reticulata*; @Gasparini2011; @Daniel2015] and house mice [*Mus domesticus*; @Potts1991; @Firman2015], while @Liu2014 found evidence for pre-copulatory, but not post-copulatory, inbreeding avoidance in an experimental study of cabbage beetles (*Colaphellus bowringi*). These empirical studies demonstrate that all combinations of adaptive pre-copulatory and post-copulatory inbreeding avoidance are possible, but no conceptual framework exists to predict *a priori* what combinations should be favoured by selection when both pre- and post-copulatory inbreeding avoidance, and polyandry, can evolve. 

Frequencies of alleles underlying active pre- and post-copulatory inbreeding avoidance and polyandry are likely to be affected by direct negative selection on phenotypes (i.e., costs). For example, females that are genetically predisposed to polyandry often pay a cost associated with searching or making themselves available to mates, thereby increasing their own risk of predation [e.g., @Rowe1988; @Ronkainen1994; @Koga1998]. Females that express pre-copulatory choice (e.g., reluctance to mate with relatives) might pay a cost of increased risk of mating failure, or harm caused by sexual conflict [@Rowe1994; @Kokko2013]. Females that express post-copulatory choice might pay an energetic cost associated with physiological or biochemical mechanisms needed to store sperm and successfully bias fertilisation [e.g., @Gasparini2011; @Tuni2013; @Fitzpatrick2014b]. If the relative costs affecting pre- and post-copulatory inbreeding avoidance differ, then alleles underlying the less costly inbreeding strategy might become fixed in the population over generations, while alleles underlying the more costly inbreeding strategy might become extinct if their effects are both costly and made redundant by the less costly strategy.

In addition to the relative importance of costs, evolution of pre- or post-copulatory inbreeding avoidance might be precluded if inbreeding avoidance is already acheived through a complementary strategy. Previous models considered the fate of a rare allele underlying inbreeding avoidance in a population initially fixed for random mating [e.g., Duthie and Reid *In press*; @Parker1979; @Parker2006; @Duthie]. Such models thereby isolate the invasion fitness of a single focal strategy, but when multiple distinct strategies affect realised inbreeding, it cannot be assumed that both will invade simultaneously, nor that invasion fitness of one inbreeding strategy will be independent of another. For example, if pre-adaptation or rapid selection results in the fixation of alleles underlying adaptive pre-copulatory inbreeding avoidance, then alleles underlying post-copulatory inbreeding avoidance might be precluded from invading a population in which post-copulatory choice is not already expressed because the effect that such invading alleles have on decreasing total inbreeding avoidance could be weak or negligible. To predict evolutionary outcomes, it is therefore necessary to consider evolution when one inbreeding avoidance strategy is initially rare, and the other strategy is common.


<!--- Rubbish: is unlikely to be simultaneous. Testing whether or not initially rare alleles underlying inbreeding avoidance can successfully invade a population Even if invasion fitness of alleles underlying inbreeding avoidance are high when mating and fertilisation is random with respect to relatedness, initial invasion of Initial evolution of pre- and post-copulatory inbreeding avoidance strategies is unlikely to be simultaneous, so to predict evolutionary outcomes, it is necessary to consider evolution when one inbreeding avoidance strategy is initially rare, and the other strategy is common. For example, if pre-adaptation or rapid selection resulted in the fixation of alleles underlying adaptive pre-copulatory inbreeding avoidance, then alleles underlying post-copulatory inbreeding avoidance might be precluded from invading a population in which post-copulatory choice is not already expressed because the effect that such invading alleles had on decreasing total inbreeding avoidance would be weak or negligible.  --->




<!--- It is therefore necessary to consider evolution of inbreeding mating strategy and inbreeding fertilisation strategy when each evolves in a population where its complementary inbreeding strategy is evolutionarily constrained or already fixed as an adaptation. --->

<!--- Overall, to predict evolution of polyandry and inbreeding strategies, it is therefore necessary to model costs associated with polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy. ---> 

  
<!--- Inbreeding, defined as breeding between relatives, directly affects inheritence of identical-by-descent alleles and the viability of inbred offspring, meaning that the decision to prefer, avoid, or tolerate (i.e., mate randomly with respect to relatedness) inbreeding is predicted to have profound effects on individual fitness [@Parker2006; @Kokko2006; @Szulkin2012; @Duthie2015a]. Viability of inbred offspring typically decreases with increasing relatedness between parents [termed 'inbreeding depression'; @Keller2002; @Charlesworth2009]. If inbreeding depression is sufficiently weak, selection for female inbreeding preference is predicted because inbreeding increases the reproductive success of a focal female's male relative, thereby increasing the number of identical-by-descent allele copies present in her offspring [@Parker1979; @Parker2006; @Kokko2006; @Duthie2015a]. However, if inbreeding depression is moderate to strong, selection for female inbreeding avoidance is predicted [Duthie and Reid *in press*; @Duthie]. Female inbreeding strategy can be enacted before or after copulation occurs [e.g., @Tuni2013; @Firman2015; @Daniel2015; @Fischer2015]. However, models of inbreeding do not consider pre-copulatory inbreeding strategy (hereafter 'inbreeding mating strategy') and post-copulatory inbreeding strategy (hereafter 'inbreeding fertilisation strategy') jointly, meaning that it is unclear when selection for either or both strategies is predicted in empirical systems.  --->

<!--- Critically, evolution of inbreeding fertilisation strategy is precluded if females only mate with one male, meaning that evolution of polyandry (defined as female multiple mating within a single reproductive bout) is intrinsically tied to female inbreeding fertilisation strategy. Although polyandry is commonplace in wild populations, the regularity with which it is observed in the wild remains theoretically puzzling because engaging in polyandry does not necessarily increase the number of offspring that a female produces, meaning that the fitness benefits associated with polyandry are not always clear [@Parker2013; @Taylor2014]. It has been hypothesised that females can acheive a net fitness benefit if polyandry provides them with additional opportunities to adjust their inbreeding through copulations with additional males [e.g., @Tregenza2002; @Akcay2007; @Lehtonen2015].  However, no models quantify the degree to which expression of biased paternity resulting from evolving inbreeding fertilisation strategy can feedback to drive evolution of polyandry in populations of potentially inbreeding females and males with biologically realistic distributions of relatedness. --->

<!--- Evolution of inbreeding fertilisation strategy might increase selection for polyandry, but evolutionary feedbacks between inbreeding fertilisation strategy and polyandry might also be contingent upon evolution of inbreeding mating strategy, thereby leading to complex evolutionary dynamics between inbreeding strategies and polyandry. For example, if females can acheive their desired degree of inbreeding through mate choice alone, then subsequent polyandry and inbreeding fertilisation strategy might be superfluous for increasing female fitness. Alternatively, if females are often unsuccessful at realising their inbreeding mating strategy due to factors such as sexual conflict over mating and resulting male coercion [e.g., @Parker2006], limited kin recognition amongst potential mates [e.g., @Penn2010], or simply the inherent stochasticity associated with mate encounters or expression of mate choice based on inbreeding [e.g., @Kokko2006; @Duthie], then selection on inbreeding fertilisation strategy might occur to reinforce inbreeding mating strategy. In empirical systems where inbreeding depression is severe and inbreeding avoidance is therefore beneficial, expression of inbreeding mating strategy and inbreeding fertilisation strategy have been observed across diverse taxa [e.g., @Gasparini2011; @Tuni2013; @Firman2015; @Fischer2015; @Daniel2015]. However, no models predict *a priori* which of these inbreeding strategies should be observed when inbreeding depression is sufficiently severe to make inbreeding avoidance adaptive. --->





<!--- Evolution of polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy will ultimately be determined by the, potentially interacting, fitness benefits and costs of each phenotype. Given severe inbreeding depression, phenotypes will increase a focal female's fitness if they cause her to avoid breeding with close relatives [@Parker1979; @Parker2006; @Kokko2006; @Duthie2015a]. However,  --->



<!--- Selection for inbreeding mating strategy versus inbreeding fertilisation strategy and associated polyandry might also depend evolutionary constraints, or on existing phenotypes in the population. For example, if phenotypes biasing fertilisation to avoid inbreeding are precluded by evolutionary constraints [@Bradshaw1991; @Futuyma2010], then inbreeding avoidance might only be possible before copulation occurs, perhaps strengthening selection for inbreeding mating strategy and weakening selection for polyandry. Alternatively, evolution of female inbreeding mating strategy might be precluded due to severely limited kin recognition or the inability to resist male coercion given sexual conflict [@Arnqvist2005a; @Parker2006; @Penn2010]. In such conditions, females might only be able to express choice through inbreeding fertilisation strategy, perhaps strengthening selection for inbreeding avoidance through polyandry and post-copulatory mechanisms. Selection for inbreeding mating or fertilisation strategy might also be weak or negligible if the strategy is redundant due to the presence of an already established adaptive inbreeding strategy (e.g., if females already successfully avoid inbreeding during mate encounters, then they might be unable to increase their fitness further by biasing fertilisation after mating has occurred). --->


<!--- Here we apply a model of female and male reproductive interactions and associated inbreeding depression in offspring viability to quantify evolution of three separate phenotypes including female tendency for polyandry, female pre-copulatory inbreeding strategy (mating strategy), and female post-copulatory inbreeding strategy (fertilisation strategy). --->

Here we use individual-based modelling and *in silico* experiments to test the hypothesis that, given severe inbreeding depression in offspring viability, evolution of post-copulatory inbreeding avoidance causes selection for evolution of polyandry. Additionally, we test the hypothesis that costs associated with polyandry and inbreeding strategies will strongly affect evolution of each such that selection for pre-copulatory inbreeding avoidance but not post-copulatory inbreeding avoidance will occur when pre-copulatory inbreeding avoidance is less costly than the cost of post-copulatory inbreeding avoidance, while selection for post-copulatory inbreeding avoidance but not pre-copulatory inbreeding avoidance will occur when pre-copulatory inbreeding avoidance is more costly than the cost of post-copulatory inbreeding avoidance. Finally, we test the hypothesis that evolution of one inbreeding strategy will be precluded if it is introduced into a population that is already fixed for a complementary inbreeding strategy that is adaptive. We thereby provide a framework for predicting evolution of pre-copulatory and post-copulatory inbreeding avoidance across reproductive systems with different relative costs and strong inbreeding depression in offspring viability.


<!--- that constraints on evolution of one inbreeding strategy (e.g., inbreeding mating strategy) will increase the strength of selection on evolution of a complementary inbreeding strategy (e.g., inbreeding fertilisation strategy), and that --->


******************************

Model
===================================================

We track interactions among discrete individuals in a small focal population that persists over multiple generations (key individual traits, parameter values, and variables are described in Table 1). Individuals within this population are either female or male, and can be related to each other if they share a common ancestor. We record the coefficient of kinship ($k$), defined as the probability that a randomly selected homologous allele from each individual is identical-by-descent [@Lynch1998], between all pairs of individuals in each generation using the population pedigree [see @Boyce1983; @Duthie]. At the start of each generation, each female pays up to three independent costs of (1) tendency to engage in polyandry ($c_{P}$), (2) mating strategy with respect to inbreeding ($c_{M}$), and (3) fertilisation strategy with respect to inbreeding ($c_{F}$). The number of males that a focal female mates with ($N_{males}$) is determined by the effects of 20 alleles ($P_{a}$) across 10 diploid loci that combine additively to determine her genotype ($P_{g}$), and ultimately her phenotype for tendency to engage in polandry ($P_{p}$). A focal female's choice of mate(s) is affected by 20 alleles ($M_{a}$) across 10 diploid loci that combine additively to affect her genotype ($M_{g}$) and phenotype ($M_{p}$) for pre-copulatory inbreeding avoidance or preference, and kinship between the focal female and her potential mates. Similarly, after mating has occurred, post-copulatory fertilisation of a focal female's $n$ total offspring is affected by 20 alleles ($F_{a}$) across 10 diploid loci that combine additively to affect the genotype ($F_{g}$) and phenotype ($F_{p}$) of the degree to which fertilisation success is affected by kinship. After fertilisation, the viability of a focal female's $n$ offspring is decreased by inbreeding depression ($\beta$), and surviving offspring become adults. After inbreeding depression in offspring viability, $\rho$ adult male immigrants arrive in the population, then density effects reduce the entire population down to separate female ($K_{f}$) and male ($K_{m}$) carrying capacities. Over generations, we record mean values of alleles underlying polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy.

Costs
----------------------------------------------

<!--- In the case of tendency to engage in polyandry, the cost of $P_{p}$ ($c_{P}$) is interpreted biologically as a cost associated with mate searching or courtship [e.g., @Rowe1988; @Rowe1994; @Ronkainen1994; @Koga1998; @Lasley-Rasher2012]. For inbreeding mating strategy, the cost of $M_{p}$ ($c_{M}$) is interpreted biologically as a cost associated with risk of mating failure due to females being overly choosy [e.g., @Kokko2013], and for inbreeding fertilisation strategy, the cost of $F_{p}$ ($c_{F}$) is interpreted as an energetic cost associated with the physiological or biochemical mechanisms that need to be developed to bias fertilisation for inbreeding avoidance or inbreeding preference [e.g., @Gasparini2011]. --->

Values of phenotypic traits for tendency to engage in polyandry ($P_{p}$), pre-copulatory inbreeding strategy (i.e., inbreeding mating strategy, $M_{p}$), and post-copulatory inbreeding strategy (i.e., inbreeding fertilisation strategy, $F_{p}$) each have costs. Each cost independently increases the risk of female pre-mating mortality and, because generations are non-overlapping, total reproductive failure as a linear function of its associated trait. The probability that a focal female dies before mating due to the cost of polyandry is therefore $P_{p} \times c_{P}$. Similarly, the probability of pre-mating female mortality due to the cost of inbreeding mating strategy and inbreeding fertilisation strategy is $|M_{p}| \times c_{M}$ and $|F_{p}| \times c_{F}$, repectively, where $|M_{p}|$ is the absolute value of $M_{p}$ and $|F_{p}|$ is the absolute value of $F_{p}$. Absolute values are used for applying costs to inbreeding strategies because both negative and positive $M_{p}$ and $F_{p}$ bias breeding interactions with respect to kinship, while only positive values of $P_{p}$ affect a female's tendency for polyandry; zero and negative $P_{p}$ values always translate to monandrous phenotypes (see below).

Polyandry
----------------------------------------------

After costs are paid, each remaining female chooses a number of males to mate with ($N_{males}$) based on her genetically determined tendency to engage in polyandry ($P_{p}$). The exact value of $N_{males}$ is calculated by randomly sampling from a poisson distribution such that $N_{males} = Poisson(P_{p}) + 1$. This random sampling procedure causes some stochastic variation in the number of realised mates a that female chooses, with a mean $N_{males}$ of $P_{p}+1$. A value of one is added to $P_{p}$ to ensure that all females that have not paid a cost choose at least one mate, as low values of $P_{p}$ might return $Poisson(P_{p})$ values of zero.

The value of $P_{p}$ is affected by the summed values of a focal female's 20 $P_{a}$ alleles. Inheritence of all alleles models a diploid genetic architecture in which 10 $P_{a}$ alleles are randomly sampled from each parent with no physical linkage. Values of $P_{a}$ can take any real number [continuum-of-alleles model; @Kimura1965; @Lande1976; @Reeve2000; @Bocedi2014]. The tendency for polyandry genotype $P_{g}$ is therefore defined by the sum of all of a focal female's 20 $P_{a}$ values, which might be negative or positive. However, the tendency for polyandry phenotype $P_{p}$ is restricted to zero or positive values because the number of males that a female chooses to mate with cannot be negative. Hence, negative values of $P_{g}$ are translated to $P_{p}$ values of zero such that $P_{p} = 0$ when $P_{g} < 0$, but when $P_{g} \geq 0$, then $P_{p} = P_{g}$ (i.e., the phenotype value of polyandry equals the genotype value of polyandry if and only if the genotype value is greater than or equal to zero, else the phenotype value of polyandry always equals zero). The resulting $P_{p}$ is therefore modelled as a threshold trait [@Lynch1998; @Roff1996; @Roff1998; @Duthie], in which polyandry is expressed discretely at the threshold value of $P_{g} > 0$, but is determined by the consequence of continuous genetic variation arising from the effects of $P_{a}$ alleles that each contribute additively to a female's tendency toward polyandry. Negative genotype values of $P_{g}$ therefore all have the same phenotype, resulting in consistently monandrous females. In contrast, positive values of $P_{g}$ and therefore $P_{p}$ can lead to different degrees of realised polyandry in the form of discrete numbers of mates ($N_{males}$).

Mating
----------------------------------------------

Each male within the population is a potential mate for any female to choose. We therefore assume that there are no opportunity costs associated with male mating such that mating with one female would reduce a male's ability to mate with and sire the offspring of any other female [e.g., @Waser1986]. While all males are therefore available as potential mates, we assume that a female mates with her total allotment of $N_{males}$ without replacement, meaning that $N_{males}$ models the total number of distinct males that a female chooses to mate with rather than the number of times that she mates. In the unlikely event that a female's $N_{males}$ exceeds the total number of males in the population, then she mates with all of the males in the populaton. Most often, $N_{males}$ will be a small subset of the available males in the population [@Duthie], so a focal female will be able to preferentially mate with males that are close kin (high $k$), distant kin (low $k$), or non-kin ($k=0$) through the expression of her pre-copulatory inbreeding strategy phenotype ($M_{p}$). Like polyandry allele values, pre-copulatory inbreeding strategy allele values ($M_{a}$) can take any real number. However, unlike polyandry, the sum of all of a female's 20 $M_{a}$ alleles equals both her pre-copulatory inbreeding strategy genotype ($M_{g}$) and her pre-copulatory inbreeding strategy phenotype ($M_{p}$). Negative or positive values of $M_{p}$ cause a female to avoid or prefer mating with kin, respectively. Values of $M_{p}=0$ cause females to mate randomly with respect to kinship.

The probability that a focal female $i$ mates with a male $j$ with which she shares some kinship $k_{ij}$ is calculated by first assigning each male a perceived mate quality $Q^{m}_{ij}$. This quality depends upon whether the female has a strategy of avoiding mating with kin ($M_{p}<0$) or preferring mating with kin ($M_{p}>0$; if $M_{p}=0$, all males are assigned a quality of 1, $Q^{m}_{ij}=1$). If a focal female avoids mating with kin, then $Q^{m}_{ij} = (-M_{p} \times k_{ij} + 1)^{-1}$, meaning that the perceived quality of a male decreases linearly with increasingly positive values of $k_{ij}$ and increasingly negative values of $M_{p}$. If a focal female prefers mating with kin, then $Q^{m}_{ij} = M_{p} \times k_{ij} + 1$, meaning that the perceived quality of a male increases with increasingly positive values of $k_{ij}$ and $M_{p}$. After a focal female assigns all males a perceived quality, the sum of all male perceived qualities is calculated, then each male quality is divided by this sum. This transformation results in each male having a relative perceived mate quality $q^{m}_{ij}$, which is constrained to values between zero and one. The value of $q^{m}_{ij}$ then defines the probability that a focal female chooses the male as a mate; female choice is therefore stochastic, meaning that females do not always choose the male of the highest $q^{m}_{ij}$ (e.g., given $M_{p}$ values of $-2$, $-4$, $-6$, and $-8$, an outbred focal female is $1.5$, $2$, $2.5$, and $3$ times more likely to mate with a non-relative than a full-sibling $k_{ij}=0.25$, respectively). For polyandrous females that choose more than one male mate, mates are chosen iteratively such that $Q^{m}_{ij}$ and $q^{m}_{ij}$ are re-calculated for each additional mate choice, and with $Q^{m}_{ij}$ and therefore $q^{m}_{ij}$ values of already chosen males set to zero to ensure mate sampling without replacement.

Fertilisation
----------------------------------------------

The fertilisation of a female's $n$ offspring occurs after mating, with each of her $n$ offspring being assigned a sire independently and with replacement from the $N_{males}$ with which the female mated. The probability that a male mate successfully sires an offspring is affected by a female's kinship with the potential sire ($k_{ij}$) and her post-copulatory inbreeding strategy ($F_{p}$). As with polyandry and pre-copulatory inbreeding strategy phenotypes, a female's post-copulatory inbreeding strategy phenotype is determined by the summed effects of 20 post-copulatory inbreeding strategy alleles ($F_{a}$), which can take any real number. The sum of all of a female's $F_{a}$ alleles determine her post-copulatory inbreeding strategy genotype ($F_{g}$), which is identical to her post-copulatory inbreeding strategy phenotype ($F_{p}$). As with pre-copulatory inbreeding strategy phenotype ($M_{p}$), negative or positive values of $F_{p}$ correspond to inbreeding avoidance or preference respectively, and $F_{p}=0$ causes random fertilisation with respect to kinship. 

The probability that an offspring of a focal female $i$ is fertilised by one of $i$'s mates $j$ is calculated by first assigning a perceived fertilisation quality to each $j$, $Q^{f}_{ij}$. Perceived fertilisation quality $Q^{f}_{ij}$ is calculated in the same way as perceived mate quality $Q^{m}_{ij}$, such that if a focal female has a post-copulatory strategy of avoiding inbreeding ($F_{p}<0$), then the perceived quality of male $j$ is $Q^{f}_{ij} = (-F_{p} \times k_{ij} + 1)^{-1}$. If instead a focal female has a post-copulatory strategy of preferring inbreeding ($F_{p}>0$), then the perceived quality of male $j$ is $Q^{f}_{ij} = F_{p} \times k_{ij} + 1$. The perceived qualities of every male that a focal female has mated with are summed, then a relative quality ($q^{f}_{ij}$) is calculated for each male by dividing each individual male mate's $Q^{f}_{ij}$ by this sum. As with relative perceived mate quality values ($q^{m}_{ij}$), this results in values of perceived fertilisation quality $q^{f}_{ij}$ between zero and one. These $q^{f}_{ij}$ values define the probability that the offspring of a focal female $i$ is fertilised by the male $j$. Females produce $n$ offspring, meaning that $q^{f}_{ij}$ values are sampled $n$ times independently and with replacement for each female to determine the realised distribution of sires.

Mutation
----------------------------------------------

Alleles of a focal female's offspring mutate with a probability of $\mu=0.001$, with mutation being an independent event that does or does not occur for each locus. In general, loss of function mutations might be expected to be more frequent than mutations that increase the functionality of adaptations that rely on complex physiologies or behaviours. If tendency for polyandry, inbreeding mating strategies, or inbreeding fertilisation strategies rely on such complex physiologies or behaviours, then we might expect the direction of mutation to be biased (e.g., towards monandry or random mating). However, because we are interested specifically in how selection affects reproductive strategy given varying costs and inbreeding depression, we model mutation as unbiased so that selection can be isolated and inferred clearly from mean allele values.

Hence, when a mutation occurs at a locus, a new value is sampled from a random normal distribution with a mean of zero and a standard devation of mutation effect size $\mu_{SD}$, $\mathcal{N}(0, \mu_{SD})$. This new value is then added to the original value of the allele that mutates [@Kimura1965; @Lande1976; @Bocedi2014; @Duthie]. The standard deviation of the mutation effect size ($\mu_{SD}$) is set to $\sqrt{1/20}$, which scales the variance of mutation effect size to the total number of alleles affecting $P_{p}$, $M_{p}$, and $F_{p}$ phenotypes [see @Kimura1965; @Lande1976; @Bocedi2014].

Inbreeding depression
----------------------------------------------

The viability of a focal female $i$'s offspring ($\Psi_{\textrm{off}}$) decreases as a function of the coefficient of kinship between $i$ and the sire of her offspring $j$ ($k_{ij}$), and a log-linear slope of inbreeding depression $\beta$. We model selection as having an absolute effect on offspring viability (i.e., hard selection), rather than a relative effect on viability (i.e., soft selection), so that the effect of $\beta$ is consistent over generations and across different parameter combinations. Natural selection on tendency for polyandry ($P_{p}$), inbreeding mating strategy ($M_{p}$), and inbreeding fertilisation strategy ($F_{p}$) can therefore be compared across generations and parameter combinations. If offspring viability was instead relative such that the least inbred offspring had a high viability regardless of the absolute value of $k_{ij}$, then the effect of kinship coefficients and inbreeding depression slopes on offspring viability would depend on the population-wide distribution of $k_{ij}$ between females and males, making model inference more difficult. Therefore, we define offspring viability as,
\begin{equation}
\Psi_{\textrm{off}} = e^{-\beta k_{ij}}
\end{equation}
The slope $\beta$ models the number of haploid lethal equivalents that exist as deleterious recessive alleles in the gametes of $i$ and $j$, and which might combine to become homozygous in offspring and reduce viability. Equation 1 assumes that each deleterious recessive allele affects offspring viability independently, meaning that every deleterious recessive allele added will have a multiplicative affect on decreasing total viability [@Morton1956; @Mills1994], causing the log-linear relationship between parent kinship and inbreeding depression. We assume that inbreeding depression always decreases offspring viability, $\beta > 0$ (i.e., no outbreeding depression). Therefore, because $k_{ij}$ is constrained to values between zero and one, the product of $-\beta$ and $k_{ij}$ must be a value less than or equal to zero, $-\beta \times k_{ij} \leq 0$. Values of $\Psi_{\textrm{off}}$ must therefore be between zero (if $-\beta \times k_{ij}$ is very negative) and one (if $-\beta \times k_{ij} = 0$). We can therefore define $\Psi_{\textrm{off}}$ as the probability that an offspring is viable, and sample its realised viability using a Bernoulli trial.

Immigration
----------------------------------------------

After offspring viability is realised, $\rho$ adult immigrants are added to the focal population. The coefficient of kinship between an immigrant and all other individuals (including native individuals and other immigrants) always equals zero ($k_{ij}=0$). Because kinship coefficient values are calculated directly from the pedigree of the focal population, the addition of immigrants thereby introduces non-kin into the population at a constant rate and prevents the mean kinship coefficient of the population from asymptoting to a value of 1 over generations. If the focal population was instead closed ($\rho=0$), then all alleles would quickly be expected to become identical-by-descent among descendants of the ancestral population. To avoid having immigrants affect evolution of tendency for polyandry ($P_{p}$), inbreeding mating strategy ($M_{p}$), and inbreeding fertilisation strategy ($F_{p}$), immigrants are always male and can therefore be chosen based on their kinship values of zero but not actively affect reproductive decisions through the expression of $P_{p}$, $M_{p}$, or $F_{p}$. To further avoid having immigrants affect evolutionary dynamics, allele values underlying tendency for polyandry ($P_{a}$), inbreeding mating strategy ($M_{a}$), and inbreeding fertilisation strategy ($F_{a}$) are randomly sampled from normal distributions with means and standard deviations of $P_{a}$, $M_{a}$, and $F_{a}$ values equal to the means and standard deviations of those in the focal population at the time of immigration. Overall, this model of immigration effectively assumes that the focal population receives immigrants from other nearby populations that are subject to the same selection on $P_{p}$, $M_{p}$, and $F_{p}$.

Density regulation
----------------------------------------------

To avoid having unrestricted population growth over generations, we introduce a separate carrying capacity on the total number of females ($K_{f}$) and males ($K_{m}$) in the focal population following immigration [@Guillaume2009; @Duthie]. If at the end of a generation the number of females or males exceeds their respective carrying capacities, then each sex is reduced back to its $K_{f}$ or $K_{m}$ by randomly removing females and males until each sex is at its carrying capacity. Removal of females and males can be interpreted as dispersal outside the focal population, mortality, or as some combination of dispersal and mortality. The remaining females and males within the population form the next generation of adults.

Model analysis
----------------------------------------------

<!--- ---------------------------------------------------------------------- --->
<!--- -------------------- LEFT OFF HERE ----------------------------------- --->
<!--- ---------------------------------------------------------------------- --->

To analyse our model, we track mean values of alleles underlying tendency for polyandry ($P_{a}$), inbreeding mating strategy ($M_{a}$), and inbreeding fertilisation strategy ($F_{a}$) in a focal population. We present evolutionary dynamics of these mean allele values across different parameter combinations to test our four focal hypotheses (see below). We simulate up to eight possible permutations of values of costs of tendency for polyandry ($c_{P}$), inbreeding mating strategy ($c_{M}$), and inbreeding fertilisation strategy ($c_{F}$) equal to either $0$ or $0.02$ [@Duthie observed $0.02$ to be a strong cost of tendency for polyandry] for values of $\beta = 3$ ($8$ total combinations). In all simulations, we record mean values of $P_{a}$, $M_{a}$, $F_{a}$ in each generation. Each combination of parameter values simulated is replicated $40$ times, and grand mean values and standard error of means is calculated in each generation across replicate simulations. These analyses allow us to infer how allele values change over generations in response to costs, but also in response to the changing values of other alleles and therefore potentially interacting phenotypes (e.g., selection on inbreeding fertilisation strategy might be weak if polyandry is rare). For all replicates, we set the maximum number of generations to 10000, which exploratory simulations and previous modelling [@Duthie] showed to be a sufficient number of generations for inferring long-term dynamics of mean allele values and therefore selection on phenotypes. For all replicates, we also set the number of immigrants per generation to $\rho=5$, which produced a range of kin and non-kin in each generation allowing females could express inbreeding strategies. Females always produced $n=8$ offspring, which was sufficient to keep populations consistently near carrying capacities and avoid population extinction. Carrying capacities for females ($K_{f}$) and males ($K_{m}$) were both set to 100 because previous modelling has shown that populations of this size are small enough that mate encounters between kin occur with sufficient frequency for selection on inbreeding strategy, but populations are also not so small that selection is typically overwhelmed by genetic drift (Duthie and Reid *in press*).

To test our hypothesis that selection for evolution of polyandry is driven by a female's ability to bias fertilisation toward inbreeding avoidance through post-copulatory mechanisms, we compare simulations in which all three phenotypes including tendency for polyandry ($P_{p}$), inbreeding mating strategy ($M_{p}$), and inbreeding fertilisation strategy ($F_{p}$) evolve, with an identical set of simulations in which $F_{p}$ cannot evolve. In simulations without evolving $F_{p}$, we therefore include all $4$ combinations of $c_{P}=\{0,0.02\}$ and $c_{M}=\{0,0.02\}$ (but not $c{F}$). To stop $F_{p}$ from evolving, we sever the connection from $F_{a}$ to $F_{p}$ such that all $F_{g}$ genotypes resulting from $F_{a}$ cause random fertilisation with respect to kinship (i.e, $F_{p}=0$). Hence, while mutation and drift can still occur for $F_{a}$ alleles, these alleles have no phenotypic effect and polyandry cannot cause polyandrous females to benefit through an increased ability to bias fertilisation toward inbreeding avoidance (under such conditions, there can also never be a cost of $F_{p}$, meaning that $c_{F}=0$). By comparing evolution of mean $P_{p}$ values over generations when $F_{p}$ also evolves versus when $F_{p}=0$ (random fertilisation), we test whether or not evolution of inbreeding fertilisation strategy increases selection for evolution of polyandry.

To test hypotheses regarding evolution under different relative costs of phenotypes, we consider all combinations of costs using simulations in which all three traits evolve. To test the hypothesis that inbreeding mating strategy will evolve toward inbreeding avoidance ($M_{p}<0$) when mating costs are low relative to the costs of tendency for polyandry and inbreeding fertilisation strategy, but that selection for inbreeding fertilisation strategy will then be negligible ($F_{p} \approx 0$), we quantify change in $M_{a}$ and $F_{a}$ over generations in simulations where $c_{M}=0$ but $c_{P}$, $c_{F}$, or both equals $0.02$. We compare evolution in these three cost parameter value combinations with simulations in which all costs equal either $0$ or $0.02$. If our hypothesis is supported, then $M_{p}$ but not $F_{p}$ will evolve to more negative values when $c_{M}$ is relatively low than when all cost values are uniform. To test the hypothesis that inbreeding fertilisation strategy will evolve toward inbreeding avoidance ($F_{p}<0$) given low costs of polyandry and inbreeding fertilisation strategy relative to the cost of inbreeding mating strategy, but that selection on inbreeding mating strategy will be negligible ($M_{p} \approx 0$), we quantify evolution of $M_{p}$ and $F_{p}$ over generations when $c_{F}=0$, $c_{P}=0$, and $c_{M}=0.02$ . We compare evolution for this combination of cost parameter values with simulations in which all costs equal either $0$ or $0.02$. If our hypothesis is supported, then $F_{a}$ but not $M_{a}$ allele values will become more negative over generations when $c_{F}$ is relatively low than when all cost values are uniform.

To test the hypothesis that constraints on evolution of one inbreeding strategy will increase the strength of selection on a complementary strategy, we fixed inbreeding strategy phenotypes to values of zero, thereby causing either random mating ($M_{p}=0$) or the random fertilisation of offspring ($F_{p}=0$) according to a fair raffle among mates with respect to kinship. We then compare evolution of the non-fixed trait to its evolution in simulations where all traits are allowed to evolve. 

To test the hypothesis that the existence of an adaptive inbreeding strategy will decrease the strength of selection on, and thereby preclude the invasion of, a complementary strategy, we first used exploratory simulations to determine evolution of inbreeding mating strategy, and inbreeding fertilisation strategy and associated polyandry, in isolation. To test whether or not inbreeding mating avoidance was predicted to evolve when adaptive polyandry to avoid inbreeding was already established, we initiated inbreeding mating strategy allele values at zero ($M_{a}=0$), but fixed inbreeding fertilisation strategy allele values at $F_{a}=-5$ and polyandry allele values at $P_{a}=1$ (i.e., $F_{p}$ and $P_{p}$ did not evolve). Similarly, to test whether or not inbreeding fertilisation strategy evolved to avoid inbreeding, we initiated inbreeding fertilisation strategy allele values and polyandry allele values at zero ($F_{a}=0$; $P_{a}=0$), but fixed inbreeding mating strategy allele values at $M_{a}=-5$. 


******************************

Results
===================================================

We present our results by showing mean allele value changes over generations. Figures 1-5 show mean allele values of tendency for polyandry ($P_{a}$; red lines and shading), inbreeding mating strategy ($M_{a}$; blue lines and shading), and inbreeding fertilisation strategy ($F_{a}$; black lines and shading) over 10000 generations as calculated across all individuals (female and male) within a focal population over 40 replicate simulations with identical starting conditions. Solid lines represent the grand mean of replicate mean allele values, and shading around lines shows standard errors of mean allele values around the grand mean. Panels within figures show different cost combinations for tendency for polyandry ($c_{P}$), inbreeding mating strategy ($c_{M}$), and inbreeding fertilisation strategy ($c_{F}$). Figures have fewer than eight panels if some costs are not relevant because allele values are fixed, and fixed allele values are shown as horizontal lines where line height is set to the fixed allele value. Supporting Information S1 presents correlations of mean allele values across replicate simulations, which were generally weak; we found no evidence suggesting strong evolutionary divergence among replicates with identical starting conditions (e.g., as might be the case if populations stochastically evolved toward inbreeding avoidance through mate choice or fertilisation, but not both), meaning that inspecting grand means of replicate allele values accurately reflects expected evolutionary dynamics over generations.


Selection for polyandry is driven by inbreeding fertilisation strategy
----------------------------------------------

We first test our hypothesis that a focal female's ability to bias fertilisation with respect to kinship causes selection for polyandry by comparing simulations in which tendency for polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy can all evolve to simulations in which inbreeding fertilisation strategy is fixed to random mating with respect to kinship, as presented in Figures 1 and 2, respectively. Comparison of Figures 1 and 2 shows that evolution of inbreeding fertilisation strategy facilitates evolution of polyandry, particularly when costs of tendency for polyandry and inbreeding fertilisation strategy are zero. For example, in Figure 2A, tendency for polyandry allele values consistently become negative over generations ($P_{a}<0$; decreasing red line), causing populations to be monandrous. Females in these populations avoid mating with kin ($M_{a}<0$; decreasing blue line), and because these females sample mates with replacement, males that remain after their initial mate choice are more likely to be relatives, causing selection for monandry because females are most likely to succeed in avoiding inbreeding in their initial mate choice [see also @Duthie]. However, Figure 1A shows that when a focal female can also bias the probability that a particular mate sires her offspring, inbreeding fertilisation strategy evolves to inbreeding avoidance ($F_{a}<0$; decreasing black line). Consequently, the ability to bias fertilisation to avoid inbreeding causes polyandry to become adaptive, and positive values of tendency for polyandry alleles increase in frequency ($P_{a}>0$; increasing red line of Figure 1A). Although non-zero costs decrease net selection for both tendency for polyandry and inbreeding fertilisation strategy (see below), across all combinations of costs, tendency for polyandry allele values are more positive when inbreeding fertilisation strategy can also evolve. Evolution of post-copulatory inbreeding avoidance therefore greatly facilitates evolution of polyandry.


Selection given relative costs of polyandry and inbreeding strategies
----------------------------------------------

<!--- Some of these conclusions will need to be changed in light of the need for more generations of data: Strategies were concluded to be non-negligible, they they actually become negligible given a sufficient amount of time. --->

Figure 1 shows changes in mean allele values of tendency for polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy across all eight possible combinations of costs. In Figure 1A, when no phenotypes are costly, inbreeding mating strategy and inbreeding fertilisation strategy evolve to inbreeding avoidance ($M_{a}<0$ and $F_{a}<0$), and females evolve to be polyandrous ($P_{a}>0$). Costs of phenotypes had a direct effect on evolution, causing inbreeding mating strategy and inbreeding fertilisation strategy phenotypes to evolve to values closer to zero (because realisation of inbreeding strategy costs increases with phenotype absolute values) and tendency for polyandry phenotypes to evolve to values that were more negative (because realisation of polyandry costs increases with positive phenotype values).

We can use Figure 1 to test the hypothesis that inbreeding mating strategy will evolve to inbreeding avoidance ($M_{a}<0$), but inbreeding fertilisation strategy will be negligible ($F_{a} \approx 0$) when mating costs are low ($c_{M}=0$) relative to the costs of tendency for polyandry and inbreeding fertilisation strategy ($c_{P}=0.02$ or $c_{F}=0.02$) by comparing different cost combinations to the null model in which all costs equal zero (Figure 1A). Figure 1A,C,D,G show that inbreeding avoidance in mating ($M_{a}<0$) evolved consistently whenever $c_{M}=0$. When inbreeding fertilisation strategy was costly and inbreeding avoidance strategy was not costly (Figure 1D,G), inbreeding fertilisation strategy initially evolved toward inbreeding avoidance ($F_{a} < 0$), but long-term evolution of inbreeding fertilisation strategy stabilised at random mating ($F_{a} \approx 0$). However, when only tendency for polyandry was costly (Figure 1C), both inbreeding mating strategy and inbreeding fertilisation strategy evolved to inbreeding avoidance over generations ($M_{a} < 0$ and $F_{a} < 0$).

We can also use Figure 1 to test the hypothesis that inbreeding fertilisation strategy will evolve to inbreeding avoidance ($F_{a}<0$), but inbreeding mating strategy will be negligible ($M_{a} \approx 0$) when tendency for polyandry and inbreeding fertilisation strategy costs are low ($c_{P}=0$ and $c_{F}=0$) relative to the cost of inbreeding mating strategy ($c_{M}=0.02$). Figure 1B shows that inbreeding avoidance through fertilisation bias evolved ($F_{a}<0$) under these conditions. While inbreeding mating strategy initially evolved toward inbreeding avoidance ($M_{a} < 0$), long-term evolution of inbreeding mating strategy stabilised at random mating ($M_{a} \approx 0$).


Selection given constraints on evolution
----------------------------------------------

Figure 3 shows evolution of tendency for polyandry and inbreeding fertilisation strategy when inbreeding mating strategy is fixed so that females must mate randomly (blue line at $M_{a}=0$). For all cost combinations of tendency for polyandry and inbreeding fertilisation strategy (Figure 3 panels A-D), we observed selection for positive values of tendency for polyandry alleles and negative values of inbreeding fertilisation strategy alleles, which we interpret as strong evidence for evolution of polyandry and associated inbreeding avoidance through fertiisation bias. This pattern of evolution contrasts with that observed when inbreeding mating strategy was not fixed, indicating that constraints on evolution of inbreeding mating strategy increased the strength of selection for evolution of polyandry and inbreeding avoidance through fertilisation bias. For example, in Figures 1C,D,G,H, tendency for polyandry allele values were typically less than zero, reflecting evolution of monandry, and inbreeding fertilisation strategy allele values were not as negative as they were in simulations with fixed random mating (Figure 3). In general, when females were unable to avoid mating with relatives given severe inbreeding depression ($\beta=3$), selection for evolution of polyandry and post-copulatory inbreeding avoidance was strengthened.

Figure 2, which we previously contrasted with Figure 1 to test whether or not evolution of inbreeding fertilisation strategy facilitates selection for polyandry, shows evolution of tendency for polyandry and inbreeding mating strategy when inbreeding fertilisation strategy is fixed such that the sire of a focal female's offspring is randomly assigned from her mates according to a fair raffle. In all cost combinations of Figure 2 (panels A-D), tendency for polyandry allele values decreased over generations, reflecting evolution of monandry. However, values of inbreeding mating strategy alleles did not greatly differ over generations when inbreeding fertilisation strategy was fixed, meaning that the effect of fixed inbreeding fertilisation strategy on increasing selection for inbreeding avoidance through mate choice was weak or nelgigible. A weak effect is discernable in the contrast between Figure 2B and Figure 1B, in which the grand mean inbreeding mating strategy allele value is $-0.627$ when inbreeding fertilisation strategy is not fixed (Figure 1B) versus $-1.036$ when it is fixed (Figure 2B) in generation 10000. Because females have 20 alleles with additive effects on inbreeding mating strategy, an average female was therefore expected to have mean inbreeding mating strategy phenotype values of $M_{p} = -0.627 \times 20 = -12.54$ and $M_{p} = -1.036 \times 20 = -20.72$ for not fixed versus fixed inbreeding fertilisation strategy, respectively. These values would cause an outbred focal female to be $2.135$ and $4.180$ times more likely to choose a non-relative than a full sibling as a mate given not fixed versus fixed inbreeding fertilisation strategy, respectively. Therefore, when females were unable to bias fertilisation to avoid inbreeding given severe inbreeding depression ($\beta=3$), selection for evolution of pre-copulatory inbreeding avoidance was strengthened.


Selection given a pre-existing adaptive inbreeding strategy
----------------------------------------------

Figure 4 shows change in inbreeding mating strategy allele values over generations when tendency for polyandry and inbreeding fertilisation strategy alleles were fixed for adaptive values of inbreeding avoidance $P_{a}=1$ and $F_{a}=-5$. Despite that females in these simulations could already avoid inbreeding after mating occurred, inbreeding mating strategy evolved towards inbreeding avoidance given costs of $c_{M}=0$ (Figure 4A) and $c_{M}=0.02$ (Figure 4B). We therefore did not find evidence that the existence of adaptive inbreeding avoidance through fertilisation bias in any way precluded the evolution of adaptive inbreeding avoidance through mate choice.

Figure 5 shows change in tendency for polyandry and inbreeding fertilisation strategy allele values over generations when inbreeding mating strategy alleles were fixed for adaptive inbreeding avoidance $M_{a}=-5$. Existence of adaptive inbreeding avoidance through mate choice precluded evolution of polyandry for all combinations of costs (Figure 5), meaning that evolution of adpative polyandry to avoid inbreeding through inbreeding fertilisation strategy was never predicted in populations where females were already avoiding inbreeding through mate choice. Further, while inbreeding fertilisation strategy evolved toward inbreeding avoidance ($F_{a}<0$) in the absence of costs (Figure 5A,B), allele values of inbreeding fertilisation strategy were not as negative as when adaptive inbreeding avoidance through mate choice was not fixed at the outset (Figures 1A,B,C,D). We therefore found strong evidence that the existence of adaptive inbreeding avoidance through pre-copulatory mate choice precluded evolution of adaptive inbreeding avoidance through post-copulatory inbreeding avoidance through fertilisation bias.


******************************

Discussion
===================================================

Inbred offspring are typically less viable than outbred offspring, and when such inbreeding depression is strong, it is predicted to cause selection for inbreeding avoidance [Duthie and Reid *in press*; @Parker1979; @Parker2006; @Pusey1996; @Kokko2006]. In animals, inbreeding avoidance can be realised through both pre-copulatory and post-copulatory mechanisms [e.g., @Tuni2013; @Firman2015; @Daniel2015; @Fischer2015]. However, the conditions under which inbreeding avoidance is predicted to evolve via pre-copulatory, post-copulatory, or both pre- and post-copulatory mechanisms has not been modelled. There is therefore no framework for predicting what mechanisms of inbreeding avoidance are most likely to evolve in empirical populations where risk of fitness loss caused by inbreeding is high. Importantly, evolution of post-copulatory mechanisms of inbreeding avoidance requires females to mate multiply, meaning that post-copulatory inbreeding avoidance cannot occur unless polyandry has evolved in a population. Accordingly, we modelled evolution of three separate traits affecting polyandry and inbreeding avoidance, including tendency to engage in polyandry, inbreeding mating strategy (pre-copulatory), and inbreeding fertilisation strategy (post-copulatory). Using *in silico* experiments, we tested four specific hypothesis to predict evolution of tendency for polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy given diverse costs and evolutionary constraints. We found that (1) selection for polyandry was greatly strengthened given concurrent evolution of inbreeding fertilisation strategy, (2) selection was strong for low cost, and weak but not negligible for high cost, mechanisms of inbreeding avoidance, (3) constraints on evolution of pre-copulatory inbreeding avoidance greatly strengthened selection for post-copulatory inbreeding avoidance, but not vice versa, and (4) pre-existence of adaptive pre-copulatory inbreeding avoidance precluded evolution of post-copulatory inbreeding avoidance, but not vice versa. More generally, we provide a novel framework for approaching empirical studies of inbreeding avoidance, predicting evolution of polyandry and inbreeding avoidance through pre- and post-copulatory mechanisms.


Evolution of polyandry to avoid inbreeding
----------------------------------------------

The opportunity to adjust inbreeding has been widely considered as a driver of adaptive evolution of polyandry [@Tregenza2002; @Foerster2003; @Akcay2007; @Varian-Ramos2012; @Kingma2013; @Lehtonen2015; @Reid2014]. Recently, @Duthie found the conditions under which selection for polyandry to avoid inbreeding is predicted to be highly restrictive, requiring strong constraints on the availability of initial compared to additional mates, or the conditional expression of polyandry such that females only engaged in polyandry when their initial choice of mate was of low quality. However, @Duthie assumed that fertilisation of offspring was unbiased with respect to mate kinship, meaning that females could not express choice after mating had occurred. In contrast, we found that when females could express choice after mating through biased fertilisation, selection for polyandry was greatly strengthened (Figure 1A), especially when constraints restricted evolution of inbreeding avoidance through mate choice (Figure 3). The proposition that polyandry might facilitate cryptic female choice among males of varying compatibility is not new [e.g., @Zeh1997], but the existence of selection for post-copulatory inbreeding avoidance causing feedback to select for polyandry has not been formally modelled. Our model therefore has widespread implications for empirical studies of evolution of polyandry. 

We predict evolution of polyandry in populations where inbreeding depression is severe and evolution of inbreeding avoidance through post-copulatory mechanisms is not constrained. Post-copulatory mechanisms of inbreeding avoidance have been observed under these conditions in experimental systems across diverse taxa [e.g. @Pizzari2004; @Firman2008; @Bretman2009; @Gasparini2011; @Tuni2013; @Firman2015]. For example, @Pizzari2004 found that the number of sperm arriving to eggs is lower for full siblings of female red jungefowl (*Gallus gallus*) than it is for non-relatives, even after controlling for effects of order of oviposition and social familiarity. Similarly, Firman and Simmons [-@Firman2008; -@Firman2015] have shown evidence of post-copulatory inbreeding avoidance in house mice, finding fertilisation to be biased toward unrelated males independent of the order in which mating occurs [@Firman2008], perhaps due to post-copulatory mechanisms expressed through the secretion of gametic proteins originating in female's eggs [@Firman2015]. Interestingly, female house mice have also been shown to express pre-copulatory inbreeding avoidance  [@Potts1991; @Roberts2003]. Our results suggest that post-copulatory inbreeding avoidance is unlikely to evolve when females can already avoid inbreeding through pre-copulatory mechanisms (Figure 5), meaning that evolution of post-copulatory inbreeding avoidance could reasonably be hypothesised to have preceded evolution of pre-copulatory inbreeding avoidance in mice.  

Specific mechanisms of post-copulatory inbreeding avoidance are difficult to identify, but recent experimental studies have shown how females can successfully bias fetilisation after mating has occurred in both vertebrates [e.g., @Gasparini2011] and invertebrates [e.g., @Tuni2013]. For example, @Gasparini2011 artificially inseminated female guppies (*Poecilia reticulata*) with equal quantities of sperm from full-siblings and unrelated males, finding that fertilisation success was higher in non-relatives because the velocity of full siblings' sperm was reduced by females' ovarian fluids. Biased fertilisation toward non-relatives might also be accomplished through selective storage of sperm. For example, in black field crickets (*Teleogryllus commodus*), females attempt to remove the spermataphores of unwanted male mates after copulation, while male mates guard females to prevent spermatophore removal [@Bussiere2006]. Even if females are unable to remove spermatophores of unwanted mates, @Tuni2013 found that female *T. commodus* are capable of controlling the transfer of sperm to their spermatheca, most likely through physical control of the spermathecal duct, and can reduce sperm storage despite being guarded by a related male. Our results suggest that evolution of such post-copulatory inbreeding avoidance might increase selection for polyandry, especially if pre-copulatory inbreeding avoidance is costly (Figure 1) or constrained (Figure 3).


Costs of polyandry and inbreeding avoidance
----------------------------------------------

Our results show that direct negative selection on phenotypes that increase female promiscuity or choosiness with respect to kinship decrease the strength of selection for tendency for polyandry and inbreeding avoidance (Figure 1). Importantly, the cost of tendency for polyandry only decreased female fitness given tendency for polyandry phenotype values greater than zero ($P_{p}>0$), but the threshold nature of the tendency for polyandry phenotype only resulted in selection against positive tendency for polyandry allele values ($P_{a}$) when the sum over a focal female's $20$ $P_{a}$ alleles was greater than zero because summations less than zero all resulted in equivalent monandrous phenotypes ($P_{p}=0$). Hence, even when tendency for polyandry was costly, selection for more negative $P_{a}$ values weakened as the frequency of negative $P_{a}$ values increased because each individual $P_{a}$ then became less influential in causing females to be monandrous [@Duthie]. This general property of threshold traits causes maladaptive phenotypes to frequently reappear within populations due to the mutation and recombination of continuous genetic values underlying discrete phenotypes [@Roff1996; @Roff1998]. Assuming that there is continuous genetic variation underlying threshold polyandry, polyandrous phenotypes are therefore sometimes predicted to persist within populations even when costly [@Duthie], potentially creating the possibility for selection on inbreeding fertilisation strategy when polyandry is expressed. This is most evident in Figure 1C, where mean allele values for polyandry are negative (red line), but strong post-copulatory inbreeding avoidance is still predicted (grey line). Consequently, costly polyandry does not necessarily preclude evolution of adaptive post-copulatory inbreeding avoidance in populations.

A low relative cost for one inbreeding strategy (e.g., pre-copulatory inbreeding avoidance) precluded a more costly complementary inbreeding strategy from persisting in a focal population (Figure 1), meaning that long-term persistence of both pre- and post-copulatory inbreeding avoidance might not be expected in populations given cost asymmetry. Direct costs therefore strongly affected the evolution of the costly phenotype(s), meaning that quantifying costs is necessary for predicting evolution of phenotypes associated with inbreeding strategies. Quantifying direct costs of phenotypes associated with polyandry and mate choice is empirically challenging [@Pomiankowski1987; @Kokko2003; @Reid2015]. @Pomiankowski1987 categorised four types of costs that are relevant to mate choice, which we suggest are also relevant costs for polyandry, and include costs of elevated risks associated with (1) predation or (2) disease transmission, and costs incurred through (3) loss of time or (4) depletion of energy. In our model, we interpreted a cost of tendency for polyandy as an elevated risk of predation as might be incurred while searching for or courting mates [e.g., @Rowe1988; @Rowe1994], a cost of inbreeding mating strategy as a lost of time [i.e., risk of not finding a mate in time due to choosiness; e.g., @Kokko2013], and a cost of inbreeding fertilisation strategy as depletion of energy. While these costs are biologically realistic, different costs will be relevant for different populations and be realised in different ways. For example, increased risk of disease transmission has been observed for highly polyandrous females [@Roberts2015a], but such a cost would more realistically be applied to the number of realised mates a female has rather than her tendency for engaging in polyandry. Future models will therefore need to carefully consider the magnitudes and realisation of direct costs to accurately predict evolution of inbreeding strategies in populations. <!--- add Tuni citation for depletion of energy? --->

Another type of cost relevant for polyandry and inbreeding strategy is risk of male harm caused by sexual conflict [e.g., @Arnqvist2005a; @Parker2006]. We assumed that males were passive in mating encounters with females, but inbreeding theory predicts that males should benefit from a higher tolerance of inbreeding than females, leading to sexual conflict over inbreeding [@Parker1979; @Parker2006; @Kokko2006; @Duthie2015a]. Females that express the choice to avoid inbreeding when mating might therefore pay a cost of harm caused by coercion expressed by related males. This cost might itself evolve over time as male harm coevolves with female resistance [@Ronn2007; @Perry2011; @Wang2015a], and costs might vary with interactions among male non-relatives and relatives because effects of kin selection are predicted to reduce harm caused by related male suitors [@Rankin2011a]. To predict evolution of polyandry and inbreeding strategy in populations characterised by active males and sexual conflict, consideration of male inbreeding strategy and coevolution between male harm and female resistance might therefore need to be considered explicitly. 

Constraints on polyandry and inbreeding avoidance
----------------------------------------------

Our model assumed that allele values underlying tendency for polyandry, pre-copulatory inbreeding avoidance, and post-copulatory inbreeding avoidance were all initialised at zero (causing monandry, and random mating and fertilisation with respect to kinship), and phenotypes evolved simultaneously after initialisation. However, these initial conditions are likely to be atypical, as evolution of pre-copulatory and post-copulatory inbreeding avoidance from ancestral random mating and fertilisation is unlikely to occur simultaneously. Rather, initial evolution of one inbreeding strategy (e.g., pre-copulatory inbreeding avoidance) is more likely to occur in the absence of its complementary strategy (e.g., post-copulatory inbreeding avoidance) if the complementary strategy is evolutionarily constrained. Alternatively, initial evolution of one inbreeding strategy might occur in the context of an already established adaptive strategy for avoiding inbreeding. We showed that selection for post-copulatory but not pre-copulatory inbreeding avoidance was strengthened if its complementary strategy was fixed for random choice with respect to kinship, and that selection for post-copulatory but not pre-copulatory inbreeding avoidance was precluded if its complementary strategy was fixed for adaptive inbreeding avoidance.

Constraints on pre-copulatory and post-copulatory inbreeding avoidance might vary widely in empirical systems. Female mate choice might be evolutionarily constrained if females are unable to discriminate among kin and therefore incapable of choosing to avoid inbreeding [Duthie and Reid *in press*; @Penn2010]. Similarly, females might choose to avoid inbreeding, but be ecologically constrained in their choice by the availability of males if few non-relatives are available [e.g., @Kokko2006a; @Kokko2013], or if females are unable to resist male coercion given sexual conflict [@Arnqvist2005, pp. 44-91]. Females might also be unable to discriminate between sperm of relatives versus non-relatives, or be unable to successfully bias fertilisation toward non-relative's sperm. Our results suggest that such constraints on one strategy of inbreeding avoidance (pre-copulatory versus post-copulatory) will strengthen selection on a complementary strategy, perhaps making inbreeding avoidance more detectable in empirical systems.


<!--- Also: note, pre-copulatory but not post-copulatory inbreeding avoidance can occur for males ---> 


<!--- Note that females might mate multiply because first need to ensure that they get a mate at all.  \cite{Daniel2015} --->

<!---  Constraints on pre-cop: Limited kin recognition --->

<!--- BARRIERS to having both pre and post-copulatory inbreeding avoidance evolve are few, although -- all else being equal -- post-copulatory avoidance might evolve less often if there is existing mating avoidance. --->


<!---  Concluding paragraph below --->

<!--- Studies of multiple species have found evidence for female pre-copulatory inbreeding avoidance [e.g., @Lihoreau2007; @Kuriwada2011; @Kingma2013; @Fischer2015], and for post-copulatory inbreeding avoidance [e.g., @Simmons2006; @Bretman2009]. Further, evidence of both pre-copulatory and post-copulatory inbreeding avoidance has been found for a handful of well-studied species, including Trinidadian guppies [*Poecilia reticulata*; @Gasparini2011; Daniel2015] and house mice [*Mus domesticus*; @Potts1991; @Firman2015], while @Liu2014 found evidence for pre-copulatory, but not post-copulatory, inbreeding avoidance in an experimental study of cabbage beetles (*Colaphellus bowringi*). These empirical studies demonstrate that evolution of all combinations of pre-copulatory and post-copulatory inbreeding avoidance are possible, but no general modelling attempts to predict *a priori* whether or not inbreeding avoidance will be enacted before or after copulation, or if both pre-copulatory and post-copulatory inbreeding avoidance will evolve. Here we have shown that evolution of inbreeding strategies and associated polyandry are predicted to be affected by direct costs, and constraints and adaptations of complementary inbreeding strategies. --->



<!---     ----------------------------------------------------------------     --->





Acknowledgements
----------------------------------------------

This work was funded by a European Research Council Starting Grant to JMR. 

**************************

\vspace{80 mm}

Table 1
----------------------------------------------

Individual traits (A), model parameter values (B), and model variables (C) for an individual based model of the evolution of polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy.

|-------|-------------------------------------|-------------|---------------|--------------
| **A** | **Trait**                           | **Allele**  | **Genotype**  | **Phenotype**
|       | Tendency for polyandry              | $P_{a}$     | $P_{g}$       | $P_{p}$
|       | Inbreeding mating strategy          | $M_{a}$     | $M_{g}$       | $M_{p}$
|       | Inbreeding fertilisation strategy   | $F_{a}$     | $F_{g}$       | $F_{p}$
|       |                                     |             |               |
| **B** | **Description**                     | **Parameter**  | | **Defaut value(s)**
|       | Cost of tendency for polyandry                 | $c_{P}$        | | $0$, $0.02$
|       | Cost of inbreeding mating strategy             | $c_{M}$        | | $0$, $0.02$
|       | Cost of inbreeding fertilisation strategy      | $c_{F}$        | | $0$, $0.02$
|       | Focal female's number of offspring             | $n$            | | $8$
|       | Log-linear slope of inbreeding depression      | $\beta$        | | $3$
|       | Adult male immigrants per generation           | $\rho$         | | $5$
|       | Female carrying capacity                       | $K_{f}$        | | $100$
|       | Male carrying capacity                         | $K_{m}$        | | $100$
|       | Mutation rate of alleles                       | $\mu$          | | $0.001$
|       | Standard deviation of mutation effect size     | $\mu_{SD}$     | | $\sqrt{1/20}$
|       |                                                |                | |
| **C** | **Description**                                                   | | **Variable** |
|       | Coefficient of kinship                                            | | $k$          |
|       | Focal female's number of mates                                    | | $N_{males}$  |
|       | Female $i$'s perceived absolute mate quality of male $j$          | | $Q^{m}_{ij}$ |
|       | Female $i$'s perceived relative mate quality of male $j$          | | $q^{m}_{ij}$ |
|       | Female $i$'s perceived absolute fertilisation quality of male $j$ | | $Q^{f}_{ij}$ |
|       | Female $i$'s perceived relative fertilisation quality of male $j$ | | $q^{f}_{ij}$ |
|       | Viability of a focal female's offspring                           | | $\Psi_{off}$ |



![Mean allele values underlying tendency for polyandry (red lines and shading), inbreeding mating strategy (i.e., pre-copulatory choice; blue lines and shading), and inbreeding fertilisation strategy (i.e., post-copulatory choice; black lines and shading), as calculated across all individuals within a population over 10000 generations given strong inbreeding depression. Solid lines represent grand means over 40 replicate populations, and shading around solid lines show standard errors of allele values around grand means. Negative mean allele values reflect strategies of inbreeding avoidance or tendency for monandry, and positive values reflect strategies of inbreeding preference or tendency for polyandry. Panels A-H show simulations for different combinations of costs for tendency for polyandry, inbreeding mating strategy, and inbreeding fertilisation strategy. Dotted horizontal black lines in panels show values of zero on the y-axis.](Initial_Results/figures/evo_combs02_B3.png)

![Mean allele values underlying tendency for polyandry (red lines and shading) and inbreeding mating strategy (i.e., pre-copulatory choice; blue lines and shading), as calculated across all individuals within a population over 10000 generations given strong inbreeding depression when allele values underlying inbreeding fertilisation strategy (i.e., post-copulatory choice) are fixed for random fertilisation among mates (black horizontal lines where y-axes equal zero). Solid lines represent grand means over 40 replicate populations, and shading around solid lines show standard errors of allele values around grand means. Negative mean allele values reflect strategies of inbreeding avoidance or tendency for monandry, and positive values reflect strategies of inbreeding preference or tendency for polyandry. Panels A-D show simulations for different combinations of costs for tendency for polyandry and inbreeding mating strategy.](Initial_Results/figures/evo_combs02_B3_ko_F.png)

![Mean allele values underlying tendency for polyandry (red lines and shading) and inbreeding fertilisation strategy (i.e., post-copulatory choice; black lines and shading), as calculated across all individuals within a population over 10000 generations given strong inbreeding depression when allele values underlying inbreeding mating strategy (i.e., pre-copulatory choice) are fixed for random mating (blue horizontal lines where y-axes equal zero). Solid lines represent grand means over 40 replicate populations, and shading around solid lines show standard errors of allele values around grand means. Negative mean allele values reflect strategies of inbreeding avoidance or tendency for monandry, and positive values reflect strategies of inbreeding preference or tendency for polyandry. Panels A-D show simulations for different combinations of costs for tendency for polyandry and inbreeding mating strategy.](Initial_Results/figures/evo_combs02_B3_ko_M-0.png)

![Mean allele values underlying inbreeding mating strategy (i.e., pre-copulatory choice; blue lines and shading), as calculated across all individuals within a population over 10000 generations given strong inbreeding depression and the pre-existence of polyandry to avoid inbreeding (tendency for polyandry allele values equal 1, as indicated by horizontal red lines; inbreeding fertilisation strategy values equal -5, as indicated by horizontal black lines). Solid blue lines represent grand means over 40 replicate populations, and blue shading around solid lines shows standard errors of mean inbreeding mating strategy allele values around grand means. Negative mean allele values reflect a strategy of inbreeding avoidance, and positive values reflect a strategy of inbreeding preference. Panels A and B show replicate simulations in which inbreeding mating strategy is not costly and has a cost of 0.02, respectively. Dotted horizontal black lines in panels show values of zero on the y-axis.](Initial_Results/figures/evo_combs02_B3_ko_FP-5.png)

![Mean allele values underlying tendency for polyandry (red lines and shading) and inbreeding fertilisation strategy (i.e., post-copulatory choice; black lines and shading), as calculated across all individuals within a population over 10000 generations given strong inbreeding depression and the pre-existence of inbreeding avoidance in mate choice (inbreeding mating strategy values equal -5, as indicated by horizontal blue lines). Solid lines represent grand means over 40 replicate populations, and shading around solid lines show standard errors of allele values around grand means. Negative mean allele values reflect strategies of inbreeding avoidance or tendency for monandry, and positive values reflect strategies of inbreeding preference or tendency for polyandry. Panels A-D show simulations for different combinations of costs for tendency for polyandry and inbreeding mating strategy. Dotted horizontal black lines in panels show values of zero on they-axis. ](Initial_Results/figures/evo_combs02_B3_ko_M-5.png)


\vspace{180 mm}


References
----------------------------------------------





