---
title: "When, why, and how to avoid, prefer, or tolerate inbreeding"
subtitle: "https://bradduthie.shinyapps.io/inbreeding"
author: "Brad Duthie"
date: "6 March 2018"
output: 
  ioslides_presentation: 
    widescreen: yes
runtime: shiny
---


## Inbreeding depression


##

```{r lmSim, fig.show='animate', echo = FALSE}
inputPanel(
  sliderInput("Imm", label = "Immigrants", width="100%",
              min = 0.0, max = 1, value = 0, step = 0.05), 
  sliderInput("ID", label = "Inbreeding Depression", width="100%",
              min = 0.0, max = 1, value = 0, step = 0.05), 
  sliderInput("cost", label = "Strategy Cost", width="100%",
              min = 0.0, max = 1, value = 0, step = 0.05), 
  sliderInput("mu", label = "Mutation Rate", width="100%",
              min = 0.0, max = 1, value = 0, step = 0.05), 
  actionButton("mate", "New Generation"),
  actionButton("reset", "Reset")
)

ts    <- reactiveValues();
ts$df <- data.frame(gen = numeric(0), val = numeric(0));

Ds    <- observeEvent(input$mate, {
        new   <- isolate(c(dim(ts$df)[1] + 1, runif(1, 0, 1)));
        isolate(ts$df <- rbind(ts$df, new));
})

rs    <- observeEvent(input$reset, {
       ts$df <- data.frame(gen = numeric(0), val = numeric(0)); 
})

renderPlot({
  par(bg = 'transparent');
  last <- dim(ts$df)[1];
  if(last < 6){
      plot(x = 0:10, y = 0:10, type = "n", ylim = c(0, 1), cex.axis = 1.5,
           cex.lab = 1.5, xlab = "Generation", ylab = "k", bg = "transparent");
      points(x = ts$df[,1], y = ts$df[,2], pch = 20, cex = 1.5, type = "b",
             lwd = 2);
  }else{
      x0 <- last - 5;
      x1 <- last + 5;
      plot(x = x0:x1, y = x0:x1, type = "n", ylim = c(0, 1), cex.axis = 1.5,
           cex.lab = 1.5, xlab = "Generation", ylab = "k");
      points(x = ts$df[x0:x1,1], y = ts$df[x0:x1,2], pch = 20, cex = 1.5, type = "b",
             lwd = 2);
  }
})
```


## Inbreeding tolerance

## Inbreeding avoidance

## Inbreeding preference

## Parker's model




##

```{r, echo=FALSE}
OffATr <- function(r, m, mmin=1, Beta=1, c=1){
    return( (1/2)*(1+r) * (1 - exp(-c*(m - mmin - Beta*r)) ));
}
# Below is fmd for analysis and plotting
OffATrd <- function(r, m, mmin=1, Beta=1, c=1){
    return(  0.5 * (1 + r) * (exp(-c * (m - mmin - Beta * r)) * c)  );
    # Also can simplify: return(  (c/2)*(1+r)*exp(-c*(m-mmin-Beta*r))  );
} # We'll need the above to find m^{*} and \gamma^{*} 
# To find m^{*}, can use the function below
findm <- function(low.guess,high.guess,rval,mmin=1,Beta=1,c=1){
  fm  <- function(m,r=rval){ 
           OffATrd(r=rval, mmin=mmin, Beta=Beta, m=m, c=c)*(0-m) + 
             OffATr(r=rval, mmin=mmin, Beta=Beta, m=m, c=c);
         }
  lg  <- fm(m=low.guess, r=rval);
  hg  <- fm(m=high.guess,r=rval);
  if(lg > 0){
    u <- low.guess;
    l <- high.guess;
  }else{
    u <- high.guess;
    l <- low.guess;
  }
  if((fm(l) > 0 & fm(u) > 0) | (fm(l) < 0 & fm(u) < 0)){
    return("Value of m is outside the range");
  }else{
    check  <- 1;
    mguess <- 0.5 * (l+u);
    i      <- 0;
    while(abs(check) > 0.000001 & i < 1000000){
        check <- fm(r=rval, m=mguess);
        if(check > 0){
          u      <- mguess;
          mguess <- 0.5*(l+mguess); 
        }else{
          l      <- mguess;
          mguess <- 0.5*(u+mguess);
        }
        i <- i+1;
    }
    return(mguess);
  }
} # Running the below returns the estimate
fmpl  <- expression(zeta[off] == frac(1,2)*(1+r)*(1-e^{(-c*(m-m[min]-beta*r))}));
inputPanel(
    
  sliderInput("rval", label = "Relatedness", width="100%",
              min = 0.0, max = 1, value = 0, step = 0.05), 
    
  sliderInput("cval", label = "PI curve", width="100%",
              min = 0.0, max = 3, value = 1, step=0.2),
  
  sliderInput("mmin", label = "Minimum m value", width="100%",
              min = 0.0, max = 2, value = 1, step = 0.1),
  
  sliderInput("Beta", label = "Inbreeding depression", 
              width="100%", min = 0.0, max = 5, value = 0, step = 0.2)
)

renderPlot({
  cc  <- as.numeric(input$cval);
  mm  <- as.numeric(input$mmin);
  bb  <- as.numeric(input$Beta);
  rr  <- as.numeric(input$rval);
  rmm <- findm(low.guess=0,high.guess=6,rval=rr,mmin=mm,Beta=bb,c=cc);
  mzt <- OffATr(r=rr, m=rmm, mmin=mm, Beta=bb, c=cc);
  rmg <- mzt / rmm;    
  PI  <- seq(from=0,to=4,by=0.01);
  All <- OffATr(r=rr, m=PI, mmin=mm, Beta=bb, c=cc);
  par(mar=c(5,5,2,2));
  plot(PI,All,type="l",lwd=4,ylim=c(0,1),
     xlab=expression(paste("Parental investment (",italic(m),")")),
     ylab=expression(paste("IBD alleles in offspring (",zeta[off],")")),
     cex.lab=1.5,cex.axis=1.5);
  abline(h=0,lty="dotted",lwd=0.8);
  abline(a=0,b=rmg,lty="solid", lwd=2,col="blue");
  arrows(x0=rmm,y0=mzt/2,x1=rmm,y1=0,length = 0.15,angle=30,code=2,lwd=3,col="blue");
  text(x=1,y=0.8,labels=fmpl,cex=2);
  text(x=rmm,y=0.5*mzt+0.07,labels=expression(paste(italic(m)^"*")),col="blue",cex=2);
  text(x=0.5,y=rmg*0.5+0.07,labels=expression(paste(italic(gamma^"*"))),
       srt=rmg,cex=2,col="blue");
})
```